### ISSUE TITLE
Why can't the ACL be 'private'?

### ISSUE THREAD

**Issue by retorquere** [mpneuried/aws-s3-form#5]
Many of the examples AWS puts up use `private` for the acl. Is there a specific reason why it shouldn't work with this library?

**Comment by mpneuried** [comment]
i added all currently possible values:

> private | public-read | public-read-write | authenticated-read | bucket-owner-read | bucket-owner-full-control

See: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html
