### ISSUE TITLE
React Native Fork

### ISSUE THREAD

**Issue by morenoh149** [mpneuried/aws-s3-form#8]
I'm trying to upload to s3 from a react native app. Sadly this project depends on `mime` module that in turn depends on the `fs` module which react native lacks. Any interest in making this project react native compatible?

**Comment by mpneuried** [comment]
I forked the [`mime`](https://github.com/broofa/node-mime) module to [`mime-nofs`](https://github.com/mpneuried/mime-nofs) to get rid of the file system dependency.

I hope this is a solution for you ;-)

**Comment by morenoh149** [comment]
wow thanks so much.

**Comment by morenoh149** [comment]
Sadly react native lacks the `crypto` module as well. https://github.com/mpneuried/aws-s3-form/search?utf8=%E2%9C%93&q=crypto

**Comment by license2e** [comment]
@morenoh149 http://stackoverflow.com/questions/33312281/react-native-crypto-how-to-generate-hmac-in-react-native#comment54437862_33312281

"npm package `crypto-js` with RN on version 0.12.0, and it works flawlessly." - [Nader Dabit](http://stackoverflow.com/users/2864119/nader-dabit) - Oct 24 at 15:37

**Comment by mpneuried** [comment]
Hi, with version `0.3.3` i added the option `cryptoModule` to set `crypto-js` a alternative crypto engine.
Please let me know if this is a solution for you.

**Comment by morenoh149** [comment]
We abandoned client uploading but hopefully others find this useful.
